# Generated by Django 4.2 on 2025-05-15 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="special_requests",
            field=models.TextField(
                blank=True, null=True, verbose_name="Особые пожелания"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="date",
            field=models.DateField(verbose_name="Дата бронирования"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="email",
            field=models.EmailField(
                max_length=254, verbose_name="Электронная почта клиента"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="guests",
            field=models.PositiveIntegerField(verbose_name="Количество гостей"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Имя клиента"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="phone",
            field=models.CharField(
                max_length=15, verbose_name="Номер телефона клиента"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="time",
            field=models.TimeField(verbose_name="Время бронирования"),
        ),
        migrations.AlterField(
            model_name="review",
            name="approved",
            field=models.BooleanField(
                default=False, verbose_name="Одобрен для публикации"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="comment",
            field=models.TextField(verbose_name="Текст отзыва"),
        ),
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="review",
            name="email",
            field=models.EmailField(
                max_length=254, verbose_name="Электронная почта автора"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Имя автора"),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveIntegerField(
                default=5, help_text="Из 5", verbose_name="Оценка"
            ),
        ),
    ]
