# Generated by Django 4.2.18 on 2025-05-15 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_special_requests_alter_booking_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='special_requests',
        ),
    ]
